FROM python:3.7.4

# set working folder
WORKDIR /usr/src/geoapi

# add gcc for compiling speedups and curl for testing
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y build-essential && apt-get install -y curl

# install app dependencies
RUN pip install --upgrade pip setuptools wheel
COPY ./requirements.txt ./
RUN pip install -r requirements.txt

# copy app
COPY . .

# run app python -m geoapi.main
CMD [ "python", "-m", "geoapi.main"]
