version: '3'

services:
  geoapi:
    build: .
    image: tinyperegrine/geoapi:1.0
    depends_on:
      - db
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:engineTest888@db/zesty
  db:
    image: mdillon/postgis:9.6
    restart: always
    ports:
      - "5556:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: engineTest888
      POSTGRES_DB: zesty
    volumes:
      - ./init-db/:/docker-entrypoint-initdb.d/
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: